# Generated by Django 3.2.4 on 2021-07-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_update',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
