# Generated by Django 3.2.4 on 2021-07-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0002_weather_update_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather_update',
            old_name='country_code',
            new_name='country',
        ),
    ]
